library(dplyr)
par(mar=c(5,4,4,4))
power_data=read.table(file="household_power_consumption.txt", header=T, sep=";") 
wday=weekdays(as.Date(power_data$Date),abbreviate=T)
power_data=cbind(power_data,wday)
power_tbl=tbl_df(power_data)
power_dates = filter(power_tbl,Date== "1/2/2007" | Date=="2/2/2007")
hist(as.double(as.character(power_dates$Global_active_power)), col='red', main="Global Active Power", xlab="Global Active Power(kilowatts)")
dev.copy(png,file="plot1.png")
png(filename="plot1.png", width=480, height=480, units="px")
dev.off
