library(dplyr)
par(mar=c(5,4,4,4))
data=read.table(file="household_power_consumption.txt", header=T, sep=";") 
#wday=weekdays(as.Date(power_data$Date),abbreviate=T)
#data$DateTime <- paste(data$Date, data$Time)
#data$DateTime <- strptime(data$DateTime, format = "%Y-%m-%d %H:%M:%S")

data$DateTime = as.POSIXct(paste(data$Date,data$Time), format="%d/%m/%Y %H:%M:%S")
#Date_time=paste(power_data$Date,power_data$Time)
#power_data=cbind(power_data,wday,Date_time)
#power_tbl=tbl_df(data)
box = subset(data,Date== "1/2/2007" | Date=="2/2/2007")
plot(box$DateTime, as.double(as.character(box$Global_active_power)),type="n", ylab="Global Active Power(kilowatts)",xlab="")
lines(box$DateTime, as.double(as.character(box$Global_active_power)))
#plot(as.double(as.character(power_dates$Global_active_power)),wday, type="l",main="Global Active Power", ylab="Global Active Power(kilowatts)",xlab="")
dev.copy(png,file="plot2.png")
png(filename="plot2.png", width=480, height=480, units="px")
dev.off
